// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO3

package proto.SensorMetric

object SensorMetricProto extends _root_.scalapb.GeneratedFileObject {
  lazy val dependencies: Seq[_root_.scalapb.GeneratedFileObject] = Seq.empty
  lazy val messagesCompanions: Seq[_root_.scalapb.GeneratedMessageCompanion[_ <: _root_.scalapb.GeneratedMessage]] =
    Seq[_root_.scalapb.GeneratedMessageCompanion[_ <: _root_.scalapb.GeneratedMessage]](
      proto.SensorMetric.SensorMetric
    )
  private lazy val ProtoBytes: _root_.scala.Array[Byte] =
      scalapb.Encoding.fromBase64(scala.collection.immutable.Seq(
  """Chhwcm90by9TZW5zb3JNZXRyaWMucHJvdG8SBXByb3RvIrEDCgxTZW5zb3JNZXRyaWMSKQoIc2Vuc29ySWQYASABKAlCDeI/C
  hIIc2Vuc29ySWRSCHNlbnNvcklkEjsKDmF2Z1RlbXBlcmF0dXJlGAIgASgCQhPiPxASDmF2Z1RlbXBlcmF0dXJlUg5hdmdUZW1wZ
  XJhdHVyZRIyCgthdmdIdW1pZGl0eRgDIAEoAkIQ4j8NEgthdmdIdW1pZGl0eVILYXZnSHVtaWRpdHkSOwoObWluVGVtcGVyYXR1c
  mUYBCABKAJCE+I/EBIObWluVGVtcGVyYXR1cmVSDm1pblRlbXBlcmF0dXJlEjsKDm1heFRlbXBlcmF0dXJlGAUgASgCQhPiPxASD
  m1heFRlbXBlcmF0dXJlUg5tYXhUZW1wZXJhdHVyZRIyCgttaW5IdW1pZGl0eRgGIAEoAkIQ4j8NEgttaW5IdW1pZGl0eVILbWluS
  HVtaWRpdHkSMgoLbWF4SHVtaWRpdHkYByABKAJCEOI/DRILbWF4SHVtaWRpdHlSC21heEh1bWlkaXR5EiMKBndlaWdodBgIIAEoB
  UIL4j8IEgZ3ZWlnaHRSBndlaWdodGIGcHJvdG8z"""
      ).mkString)
  lazy val scalaDescriptor: _root_.scalapb.descriptors.FileDescriptor = {
    val scalaProto = com.google.protobuf.descriptor.FileDescriptorProto.parseFrom(ProtoBytes)
    _root_.scalapb.descriptors.FileDescriptor.buildFrom(scalaProto, dependencies.map(_.scalaDescriptor))
  }
  lazy val javaDescriptor: com.google.protobuf.Descriptors.FileDescriptor = {
    val javaProto = com.google.protobuf.DescriptorProtos.FileDescriptorProto.parseFrom(ProtoBytes)
    com.google.protobuf.Descriptors.FileDescriptor.buildFrom(javaProto, _root_.scala.Array(
    ))
  }
  @deprecated("Use javaDescriptor instead. In a future version this will refer to scalaDescriptor.", "ScalaPB 0.5.47")
  def descriptor: com.google.protobuf.Descriptors.FileDescriptor = javaDescriptor
}