// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO3

package proto.SensorReadingProto

object SensorReadingProtoProto extends _root_.scalapb.GeneratedFileObject {
  lazy val dependencies: Seq[_root_.scalapb.GeneratedFileObject] = Seq.empty
  lazy val messagesCompanions: Seq[_root_.scalapb.GeneratedMessageCompanion[_ <: _root_.scalapb.GeneratedMessage]] =
    Seq[_root_.scalapb.GeneratedMessageCompanion[_ <: _root_.scalapb.GeneratedMessage]](
      proto.SensorReadingProto.SensorReadingProto
    )
  private lazy val ProtoBytes: _root_.scala.Array[Byte] =
    scalapb
      .Encoding
      .fromBase64(
        scala
          .collection
          .immutable
          .Seq("""Ch5wcm90by9TZW5zb3JSZWFkaW5nUHJvdG8ucHJvdG8SBXByb3RvIswBChJTZW5zb3JSZWFkaW5nUHJvdG8SKQoIc2Vuc29yS
  WQYASABKAlCDeI/ChIIc2Vuc29ySWRSCHNlbnNvcklkEiwKCXRpbWVzdGFtcBgCIAEoCUIO4j8LEgl0aW1lc3RhbXBSCXRpbWVzd
  GFtcBIyCgt0ZW1wZXJhdHVyZRgDIAEoAkIQ4j8NEgt0ZW1wZXJhdHVyZVILdGVtcGVyYXR1cmUSKQoIaHVtaWRpdHkYBCABKAJCD
  eI/ChIIaHVtaWRpdHlSCGh1bWlkaXR5YgZwcm90bzM=""")
          .mkString
      )
  lazy val scalaDescriptor: _root_.scalapb.descriptors.FileDescriptor = {
    val scalaProto = com.google.protobuf.descriptor.FileDescriptorProto.parseFrom(ProtoBytes)
    _root_.scalapb.descriptors.FileDescriptor.buildFrom(scalaProto, dependencies.map(_.scalaDescriptor))
  }
  lazy val javaDescriptor: com.google.protobuf.Descriptors.FileDescriptor = {
    val javaProto = com.google.protobuf.DescriptorProtos.FileDescriptorProto.parseFrom(ProtoBytes)
    com.google.protobuf.Descriptors.FileDescriptor.buildFrom(javaProto, _root_.scala.Array())
  }
  @deprecated("Use javaDescriptor instead. In a future version this will refer to scalaDescriptor.", "ScalaPB 0.5.47")
  def descriptor: com.google.protobuf.Descriptors.FileDescriptor = javaDescriptor
}
